---
test:
  stage: test
  image: python:3-buster
  before_script:
    - curl -sL https://taskfile.dev/install.sh | sh
    - mv ./bin/task /usr/local/bin
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --no-interaction
  script:
    - task lint
    - task test
