---
# yamllint disable rule:line-length
language: node_js

node_js:
  - 8
  - 10

services:
  - docker

jobs:
  include:
    - name: Test
      install:
        - docker-compose up -d
        - pip install -r requirements.txt
      script:
        - pytest .
